# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# IP: ip/blk_mem_gen_sine/blk_mem_gen_sine.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_sine || ORIG_REF_NAME==blk_mem_gen_sine} -quiet] -quiet
