# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/Modelsim/win64
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.cache/wt [current_project]
set_property parent.project_path D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/BaiduNetdiskDownload/DA_HDMI/sin.coe
add_files D:/BaiduNetdiskDownload/DA_HDMI/triangle.coe
add_files D:/BaiduNetdiskDownload/DA_HDMI/square.coe
add_files D:/BaiduNetdiskDownload/DA_HDMI/sawtooth.coe
read_verilog -library xil_defaultlib {
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/video_define.v
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/background.v
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/grid.v
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/key_debounce.v
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/timing_gen.v
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/wave.v
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/top.v
}
read_vhdl -library xil_defaultlib {
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/SyncAsync.vhd
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/SyncAsyncReset.vhd
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/ClockGen.vhd
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/DVI_Constants.vhd
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/OutputSERDES.vhd
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/TMDS_Encoder.vhd
  D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/new/rgb2dvi.vhd
}
read_ip -quiet D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_sine/blk_mem_gen_sine.xci
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_sine/blk_mem_gen_sine_ooc.xdc]

read_ip -quiet D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_square/blk_mem_gen_square.xci
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_square/blk_mem_gen_square_ooc.xdc]

read_ip -quiet D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_triangle/blk_mem_gen_triangle.xci
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_triangle/blk_mem_gen_triangle_ooc.xdc]

read_ip -quiet D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_sawtooth/blk_mem_gen_sawtooth.xci
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_sawtooth/blk_mem_gen_sawtooth_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files D:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/constrs_1/new/cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
