set_property PACKAGE_PIN F20 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN E1 [get_ports tmds_clk_p]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN M6 [get_ports HDMI_en]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_en]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN K1 [get_ports {tmds_data_p[2]}]
set_property PACKAGE_PIN H2 [get_ports {tmds_data_p[1]}]
set_property PACKAGE_PIN G1 [get_ports {tmds_data_p[0]}]


set_property PACKAGE_PIN M13 [get_ports key_freq]
set_property PACKAGE_PIN K14 [get_ports key_type]
set_property IOSTANDARD LVCMOS33 [get_ports key_freq]
set_property IOSTANDARD LVCMOS33 [get_ports key_type]

set_property PACKAGE_PIN L13 [get_ports key_mode]
set_property IOSTANDARD LVCMOS33 [get_ports key_mode]


set_property PACKAGE_PIN E16 [get_ports adda_gnd]
set_property PACKAGE_PIN F14 [get_ports {ad_data[0]}]
set_property PACKAGE_PIN F13 [get_ports {ad_data[1]}]
set_property PACKAGE_PIN E14 [get_ports {ad_data[2]}]
set_property PACKAGE_PIN E13 [get_ports {ad_data[3]}]
set_property PACKAGE_PIN D15 [get_ports {ad_data[4]}]
set_property PACKAGE_PIN D14 [get_ports {ad_data[5]}]
set_property PACKAGE_PIN B13 [get_ports {ad_data[6]}]
set_property PACKAGE_PIN C13 [get_ports {ad_data[7]}]
set_property PACKAGE_PIN A13 [get_ports ad_clk]
set_property PACKAGE_PIN C14 [get_ports da_clk]
set_property PACKAGE_PIN A16 [get_ports {da_data[7]}]
set_property PACKAGE_PIN A15 [get_ports {da_data[6]}]
set_property PACKAGE_PIN B16 [get_ports {da_data[5]}]
set_property PACKAGE_PIN B15 [get_ports {da_data[4]}]
set_property PACKAGE_PIN B18 [get_ports {da_data[3]}]
set_property PACKAGE_PIN B17 [get_ports {da_data[2]}]
set_property PACKAGE_PIN A19 [get_ports {da_data[1]}]
set_property PACKAGE_PIN A18 [get_ports {da_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {da_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports adda_gnd]
