# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_sawtooth/blk_mem_gen_sawtooth.xci
# IP: The module: 'blk_mem_gen_sawtooth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_sawtooth/blk_mem_gen_sawtooth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_sawtooth'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_sawtooth/blk_mem_gen_sawtooth.xci
# IP: The module: 'blk_mem_gen_sawtooth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/BaiduNetdiskDownload/DA_HDMI/DA_HDMI.srcs/sources_1/ip/blk_mem_gen_sawtooth/blk_mem_gen_sawtooth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_sawtooth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
